<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>Latest</LangVersion>
    <OutputType>Exe</OutputType>
    <AssemblyVersion>0.0.21.0</AssemblyVersion>
    <BaseOutputPath>.\bin</BaseOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0-preview.4.25258.110" />
    <PackageReference Include="ModelContextProtocol" Version="0.3.0-preview.4" />
    <PackageReference Include="Siemens.Collaboration.Net.OperatingSystem.Windows" Version="3.0.1725521661" />
    <PackageReference Include="Siemens.Collaboration.Net.TiaPortal.Openness.Resolver" Version="2.0.1765367256" />
    <PackageReference Include="Siemens.Collaboration.Net.TiaPortal.Packages.Openness" Version="21.0.1765349347" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Management" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="tests\**" />
    <None Include="tests\**" />
  </ItemGroup>
</Project>
